### ISSUE TITLE
Syntax error calling twitter-cleanup --help

### ISSUE THREAD

**Issue by klauern** [cuducos/twitter-cleanup#13]
```
twitter-cleanup --help
Traceback (most recent call last):
  File "C:\Users\klauer\scoop\apps\python\current\scripts\twitter-cleanup-script.py", line 11, in <module>
    load_entry_point('twitter-cleanup==0.0.2', 'console_scripts', 'twitter-cleanup')()
  File "c:\users\klauer\scoop\apps\python\3.7.0\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\klauer\scoop\apps\python\3.7.0\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "c:\users\klauer\scoop\apps\python\3.7.0\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "c:\users\klauer\scoop\apps\python\3.7.0\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\klauer\scoop\apps\python\3.7.0\lib\site-packages\twitter_cleanup\__init__.py", line 3, in <module>
    from tweepy import API, Cursor
  File "c:\users\klauer\scoop\apps\python\3.7.0\lib\site-packages\tweepy\__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "c:\users\klauer\scoop\apps\python\3.7.0\lib\site-packages\tweepy\streaming.py", line 358
    def _start(self, async):
                         ^
SyntaxError: invalid syntax
```

**Comment by cuducos** [comment]
Hi @klauern, the `README.rst` asks for Python 3.6, but I see you're using 3.7: `File "c:\users\klauer\scoop\apps\python\3.7.0…"`. We cannot run on Python 3.7 because [Tweepy](http://www.tweepy.org/) is not Python 3.7 ready.
