### ISSUE TITLE
Environmental Variables not found

### ISSUE THREAD

**Issue by jorged702** [cuducos/twitter-cleanup#17]
After Installation I set up the variables as environmental variables in system properties, as well as in the .env file. ( I might have misplaced the .env file in the wrong directory) 

I am getting this error: 
`C:\Users\Jorge>twitter-cleanup --help
Traceback (most recent call last):
  File "C:\Users\Jorge\AppData\Local\Programs\Python\Python36\Scripts\twitter-cleanup-script.py", line 11, in <module>
    load_entry_point('twitter-cleanup==0.0.5', 'console_scripts', 'twitter-cleanup')()
  File "c:\users\jorge\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\jorge\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "c:\users\jorge\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "c:\users\jorge\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\jorge\appdata\local\programs\python\python36\lib\site-packages\twitter_cleanup\__init__.py", line 5, in <module>
    from twitter_cleanup.authentication import authentication
  File "c:\users\jorge\appdata\local\programs\python\python36\lib\site-packages\twitter_cleanup\authentication.py", line 37, in <module>
    authentication = Authentication()
  File "c:\users\jorge\appdata\local\programs\python\python36\lib\site-packages\twitter_cleanup\authentication.py", line 12, in __init__
    self.consumer_key = config("TWITTER_CONSUMER_KEY")
  File "c:\users\jorge\appdata\local\programs\python\python36\lib\site-packages\decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "c:\users\jorge\appdata\local\programs\python\python36\lib\site-packages\decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "c:\users\jorge\appdata\local\programs\python\python36\lib\site-packages\decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: TWITTER_CONSUMER_KEY not found. Declare it as envvar or define a default value.`

**Comment by jorged702** [comment]
I am also kinda new to this, I made a file in notepad with the info from the Readme and then just saved it as .env don't know if that is the proper way to do it

**Comment by jorged702** [comment]
Nvm for some reason I just rebooted my computer and it worked thx tho.
