### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tweepy'

### ISSUE THREAD

**Issue by Daviey** [cuducos/twitter-cleanup#22]
Fresh installation, with the environmental variables set:

```
❯ twitter-cleanup inactive 365
Traceback (most recent call last):
  File "/usr/local/bin/twitter-cleanup", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/twitter_cleanup/__main__.py", line 14, in cli
    context.obj = {"cleanup": TwitterCleanup(assume_yes=yes)}
  File "/usr/local/lib/python3.8/dist-packages/twitter_cleanup/__init__.py", line 16, in __init__
    self.api = API(auth.tweepy, wait_on_rate_limit=True)
AttributeError: 'NoneType' object has no attribute 'tweepy'
```

It seems that `auth` is not an object, but just None.

**Comment by cuducos** [comment]
Good catch!

**Comment by Daviey** [comment]
Nice, thanks for fixing this so quickly!!
