### ISSUE TITLE
TypeError: 'length' is an invalid keyword argument for __new__()

### ISSUE THREAD

**Issue by masapasa** [cuducos/twitter-cleanup#23]
/python3.8/site-packages/twitter_cleanup/user.py", line 28, in last_status_before
    return self.status.created_at < datetime.now() - timedelta(**kwargs)
TypeError: 'length' is an invalid keyword argument for __new__()

**Comment by cuducos** [comment]
Hi @masapasa 

Would mind sharing more details, like the command or script you're using and the full traceback?

Many thanks

**Comment by masapasa** [comment]
`twitter-cleanup inactive 30

Traceback (most recent call last):
  File "bin/twitter-cleanup", line 8, in <module>
    sys.exit(cli())
  File "lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "lib/python3.8/site-packages/twitter_cleanup/__main__.py", line 22, in inactive
    context.obj["cleanup"].unfollow_inactive_for(days=days)
  File "lib/python3.8/site-packages/twitter_cleanup/__init__.py", line 66, in unfollow_inactive_for
    should_unfollow = user.last_status_before(**kwargs)
  File "lib/python3.8/site-packages/twitter_cleanup/user.py", line 28, in last_status_before
    return self.status.created_at < datetime.now() - timedelta(**kwargs)
TypeError: 'length' is an invalid keyword argument for __new__()`

**Comment by masapasa** [comment]
Hi @cuducos how can i fix it? thanks!

**Comment by cuducos** [comment]
You don't have to fix it, it is already fixed in the linked commit above. Just pull the newest version with `git pull origin master`.
