### ISSUE TITLE
botometer.NoTimelineError: user has no tweets in timeline

### ISSUE THREAD

**Issue by mateuspontes** [cuducos/twitter-cleanup#8]
Deal with the error when user has no tweets in timeline

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cleanup.py", line 130, in soft_block_bots
    if user.is_bot():
  File "cleanup.py", line 72, in is_bot
    if self.protected or not self.botometer_result:
  File "cleanup.py", line 67, in botometer_result
    result = self.botometer.check_account(self.id)
  File "/Users/mateus.pontes/.virtualenvs/twitter-cleanup/lib/python3.6/site-packages/botometer/__init__.py", line 128, in check_account
    raise NoTimelineError(payload['user'])
botometer.NoTimelineError: user '{'id_str': '1013973434743885824', 'screen_name': 'ElieneO85015636'}' has no tweets in timeline
>>> cleanup.soft_block_bots(threshold=0.68)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cleanup.py", line 130, in soft_block_bots
    `threshold` (defaults to 0.75 in User class)."""
  File "cleanup.py", line 72, in is_bot
    self._botometer_result = result.get("cap", {}).get("universal")
  File "cleanup.py", line 67, in botometer_result
    try:
  File "/Users/mateus.pontes/.virtualenvs/twitter-cleanup/lib/python3.6/site-packages/botometer/__init__.py", line 128, in check_account
    raise NoTimelineError(payload['user'])
botometer.NoTimelineError: user '{'id_str': 'XXXXXXXXXX', 'screen_name': 'XXXXXXXXXX'}' has no tweets in timeline
```

**Comment by cuducos** [comment]
Closed in favor of #1
